version: "3.8"

services:
  focal:
    image: quay.io/stackstorm/packagingrunner
    working_dir: /root/st2-packages
    volumes_from:
      - container:st2-packages-vol
    environment:
      - BUILDNODE=focalbuild
      - TESTNODE=focaltest
      - ST2_PACKAGES=st2
    links:
      - focalbuild
      - focaltest
      - rabbitmq
      - mongodb
      - redis

  ## Package build nodes
  #
  focalbuild:
    image: stackstorm/packagingbuild:focal
    volumes_from:
      - container:st2-packages-vol


  ## Package testing nodes
  #
  focaltest:
    image: stackstorm/packagingtest:focal-systemd
    privileged: true
    cgroup: host
    volumes_from:
      - container:st2-packages-vol
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

  rabbitmq:
    image: rabbitmq:3.12-management
    privileged: true
    hostname: rabbit
    ports:
      - "15672:15672"  # managment plugin port
      - "5672:5672"

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
